// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FROM_FIREBASE',
    appId: 'FROM_FIREBASE',
    messagingSenderId: 'FROM_FIREBASE',
    projectId: 'FROM_FIREBASE',
    authDomain: 'FROM_FIREBASE',
    storageBucket: 'FROM_FIREBASE',
    measurementId: 'FROM_FIREBASE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FROM_FIREBASE',
    appId: 'FROM_FIREBASE',
    messagingSenderId: 'FROM_FIREBASE',
    projectId: 'FROM_FIREBASE',
    storageBucket: 'FROM_FIREBASE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FROM_FIREBASE',
    appId: 'FROM_FIREBASE',
    messagingSenderId: 'FROM_FIREBASE',
    projectId: 'FROM_FIREBASE',
    storageBucket: 'FROM_FIREBASE',
    iosBundleId: 'YOUR_BUNDLE_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'FROM_FIREBASE',
    appId: 'FROM_FIREBASE',
    messagingSenderId: 'FROM_FIREBASE',
    projectId: 'FROM_FIREBASE',
    storageBucket: 'FROM_FIREBASE',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'FROM_FIREBASE',
    appId: 'FROM_FIREBASE',
    messagingSenderId: 'FROM_FIREBASE',
    projectId: 'FROM_FIREBASE',
    authDomain: 'FROM_FIREBASE',
    storageBucket: 'FROM_FIREBASE',
    measurementId: 'FROM_FIREBASE',
  );
}