class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      // Splash Screen
      'lets_started': "Let's Started",
      
      // Onboarding
      'track_cycle_easily': 'Track Your Cycle Easily',
      'track_cycle_desc': 'Monitor your period, ovulation,\nand health in one place.',
      'chat_dr_sia': 'Talk to Dr. Sia AI Chatbot',
      'chat_dr_sia_desc': 'Ask anything about period\nhealth safely.',
      'safe_community': 'Safe Community &\nTrusted Products',
      'safe_community_desc': 'Connect & shop with\nconfidence.',
      'next': 'Next',
      'skip': 'Skip',
      
      // Profile Completion
      'complete_profile': 'Complete Your Profile',
      'name_optional': 'Name (optional)',
      'age_group': 'Age Group',
      'cycle_length': 'Cycle Length (days)',
      'last_period_date': 'Last Period Date',
      'period_duration': 'Period Duration (days)',
      'continue_btn': 'Continue',
      'invalid_date': 'Invalid date format',
      'fill_required': 'Please fill in all required fields',
      'period_days': 'days',
      
      // Home Screen
      'hi': 'Hi',
      'quick_actions': 'Quick Actions',
      'chat_ai': 'AI Chat',
      'view_tracker': 'Tracker দেখুন',
      'chat_with_ai': 'AI এর সাথে Chat',
      'log_symptoms': 'Symptoms\nলিখুন',
      'shop': 'Shop',
      'community': 'Community',
      'article': 'Article',
      'articles': 'Articles',
      'helpline': 'Helpline',
      'day_of_cycle': 'Day',
      'of_your_cycle': 'of your cycle,',
      'feeling': 'Feeling',
      'low_energy': 'Low Energy 💙',
      'reminder': 'Reminder',
      // 'next_period': 'পরবর্তী Period ৫ দিনে',
      'shurokkha': 'Shurokkha',
      'women_health': 'Women Health App',

      // Settings Screen
      'settings': 'Settings',
      'change_language': 'Change Language',
      'change_pin': 'Change PIN',
      'privacy_policy': 'Privacy Policy',
      'notifications': 'Notifications',
      'logout': 'Logout',
      'account_security': 'Account & Security',
      'privacy_data': 'Privacy & Data',
      'dark_mode': 'Enable Dark Mode',
      'delete_data': 'Delete All Data',
      'your_data_safe': 'Your data is safe and secure',
      'tips_messages': 'Tips & motivational messages',
      'select_language': 'Select Language',
      'english': 'English',
      'bengali': 'বাংলা',

      // PIN
      'set_pin': 'Set PIN',
      'enter_pin': 'Enter PIN',
      'pin_must_be_4': 'PIN must be 4 digits',
      'pin_mismatch': 'PINs do not match',
      'incorrect_pin': 'Incorrect PIN',
      'confirm_pin': 'Confirm PIN',

      // Navigation
      'home': 'Home',
      'calendar': 'Calendar',
      'chat': 'Chat',
      'store': 'Store',
      
      // Period Tracker
      'period_tracker': 'Period Tracker',
      'cycle_info': 'Cycle সম্পর্কে তথ্য',
      'track_period': 'আপনার Period Track করুন',
      
      // Chat
      'chat_with_dr_sia': 'Chat with Dr. Sia',
      'ask_question': 'Ask your question here...',
      
      // Community
      'join_community': 'Join Our Community',
      'share_experiences': 'Share experiences with others',
      
      // Shop
      'trusted_products': 'Trusted Products',
      'shop_essentials': 'Shop Health Essentials',
      
      // Articles
      'health_articles': 'Health Articles',
      'read_articles': 'Read helpful articles',
      
      // Helpline
      'emergency_helpline': 'Emergency Helpline',
      'need_help': 'Need help? Contact our helpline',
      
      // Health Tips
      'health_tips': 'Health Tips',
      'daily_tips': 'Daily health tips and advice',
      
      // Period Reminder Card
      'period_reminder': 'Period Reminder',
      'active_period': 'Active Period',
      'of': 'of',
      'day_remaining': 'day remaining',
      'days_remaining': 'days remaining',
      'next_period_in': 'Next Period in',
      'day': 'day',
      'days': 'days',
      'you_are_on_day': 'You are on day',
      'cycle_progress': 'Cycle Progress',
      'current_day': 'Current Day',
      'days_until': 'Days until',
      'days_left': 'Days Left',
      'next_next_period': 'next period',
      'phase_menstruation': 'Phase: Menstruation',
      'phase_follicular': 'Phase: Follicular (High Energy)',
      'phase_ovulation': 'Phase: Ovulation (Peak)',
      'phase_luteal': 'Phase: Luteal (Rest)',
      'phase_cycle_begin': 'Phase: Cycle Begin',
      
      // Additional Translations for Screens
      'flow_intensity': 'Flow Intensity',
      'pain_levels': 'Pain Levels',
      'mood': 'Mood',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'no_pain': 'No Pain',
      'moderate': 'Moderate',
      'severe': 'Severe',
      'good': 'Good',
      'neutral': 'Neutral',
      'none': 'None',
      'emotional': 'Emotional',
      'anxious': 'Anxious',
      'energetic': 'Energetic',
      'save_symptoms': 'Save Symptoms',
      'symptoms_logged': 'Symptoms logged successfully!',
      'online_ready': 'Online & Ready to Help',
      'sort_by': 'Sort by',
      'newest': 'Newest',
      'oldest': 'Oldest',
      'short_reads': 'Short Reads',
      'filter': 'Filter',
      'all': 'All',
      'emergency': 'Emergency',
      'no_saved_articles': 'No saved articles yet',
      'bookmark_articles': 'Bookmark articles to save them here',
      'online': 'Online',
      'status_online': 'Status',
      'period': 'Period',
      'follicular': 'Follicular',
      'ovulation': 'Ovulation',
      'cycle_phases': 'Cycle Phases',
      'your_menstrual_phase': 'Your menstrual phase',
      'fertile_window': 'Fertile window (most fertile)',
      'pms_period': 'PMS Period',
      'pms_description': '2-3 days before period',
      'set_your_period': 'Set Your Period',
      'choose_preferred_method': 'Choose your preferred method',
      'period_start_date': 'Period Start Date',
      'set_when_started': 'Set when your period started',
      'period_start_end': 'Period Start & End',
      'set_both_dates': 'Set both start and end dates',
      'set_period_date': 'Please set your period date to see predictions.',
      'current_cycle': 'Current Cycle',
      'period_in_days': 'In {days} days',
      'fertility_ovulation': 'Fertility & Ovulation',
      'high_fertility': '🔥 High fertility - Peak window now!',
      'ovulation_in': 'Ovulation in {days} days',
      'pms_prediction': 'PMS Prediction',
      'pms_upcoming': 'PMS starts in {days} days',
      'cycle_history': 'Cycle History',
      'future_predictions': 'Future Predictions',
      'welcome_hafsa': 'Welcome to Hafsa AI',
      'personal_health_companion': 'Your personal health companion',
      'private_secure': '100% Private & Secure\nBiomedical AI Assistant',
      'suggested_questions': 'Suggested Questions',
      'ask_hafsa': 'Ask Hafsa...',
      'daily_tip': 'Daily Tip',
      'search_articles': 'Search articles...',
      'sort_by_label': 'Sort by:',
      'articles_tab': 'Articles',
      'favorites_tab': 'Favorites',
      'no_articles': 'No articles found',
      'no_favorites': 'No bookmarked articles yet',
      'bookmark_to_save': 'Bookmark articles to save them here',
      
      // Health Tips Screen
      'menstrual_health': 'Menstrual Health & Hygiene',
      'sanitary_products': 'Sanitary Products Awareness',
      'proper_hygiene': 'Proper Hygiene Practices',
      'period_comfort': 'Period Comfort & Cramps Relief',
      'nutrition_energy': 'Nutrition & Energy (Bangladeshi Foods)',
      'iron_rich_foods': 'Iron-Rich Foods',
      'hydration': 'Hydration',
      'energy_boosters': 'Energy Boosters',
      'avoiding_heavy_foods': 'Avoiding Heavy Foods',
      'pms_mood': 'PMS & Mood Management',
      'emotional_support': 'Emotional Support Tips',
      'daily_routine': 'Daily Routine Adjustments',
      'exercise_lifestyle': 'Exercise & Lifestyle',
      'light_exercise': 'Light Exercise Recommendations',
      'healthy_habits': 'Healthy Habits',
      'fertility_ovulation_awareness': 'Fertility & Ovulation Awareness',
      'fertile_window_tips': 'Fertile Window Tips',
      'family_planning': 'Family Planning Tips',
      
      // Helpline Screen
      'select_category': 'Select Category',
      'emergency_services': 'Emergency Services',
      'mental_health_support': 'Mental Health Support',
      'women_health_services': 'Women Health Services',
      'available': 'Available',
      'verified': 'Verified',
      'emergency_medical': 'For urgent medical emergencies and critical situations',
      'mental_health_counseling': 'Mental health support and counseling services (Free & Confidential)',
      'reproductive_health': 'Sexual & Reproductive Health (SRH) services and counseling',
      'call_now': 'Call Now',
      'copy_number': 'Copy Number',
      
      // Community Screen
      'community_title': 'Shurokkha Community',
      'chat_rooms': 'Chat Rooms',
      'peer_support_chat': 'Peer Support Chat',
      'create_new_post': 'Create New Post',
      'share_your_experience': 'Share your experience...',
      'select_feeling': 'Select your feeling',
      'select_topic': 'Select topic',
      'write_message': 'Write your message',
      'photo': 'Photo',
      'location': 'Location',
      'private': 'Private',
      'safe_space': 'Safe Space',
      'anonymous_username': 'Anonymous User',
      'soon_available': 'Soon available',
      'post_created': 'Post created ✓',
      'shared_experiences': 'Shared Experiences',
      'people_shared': 'people have shared their experience',
      'post_comment': 'Post a Comment',
      'write_comment': 'Share your thought or experience...',
      'post': 'Post',
      'supports': 'Supports',
      'comments': 'Comments',
      'saves': 'Saves',
      'view_all': 'View All',
      'expert_reply': 'Expert Reply',
      
      // Shop Screen - Products
      'ultra_comfort_pads': 'Ultra Comfort Pads',
      'menstrual_cup': 'Menstrual Cup',
      'wellness_kit': 'Wellness Kit',
      'night_pads': 'Night Pads',
      'organic_cotton_pads': 'Organic Cotton Pads',
      'pain_relief_kit': 'Pain Relief Kit',
      'heating_pad': 'Heating Pad',
      'category_pads': 'Pads',
      'category_cups': 'Cups',
      'category_wellness': 'Wellness',
      'category_hygiene': 'Hygiene',
      'category_nutrition': 'Nutrition',
      'best_seller': 'Best Seller',
      'recommended': 'Recommended',
      'add_to_cart': 'Add to Cart',
      'buy_now': 'Buy Now',
      'rating': 'Rating',
      'original_price': 'Original Price',
      'read_more': 'Read More',
      
      // Article Screen
      'article_understanding_cycle': 'Understanding Your Menstrual Cycle',
      'article_period_myths': 'Period Myths Debunked',
      'article_natural_remedies': 'Natural Remedies for Period Pain',
      'article_nutrition_tips': 'Nutrition Tips for Better Cycles',
      'article_mental_health': 'Mental Health & Your Cycle',
      'article_eco_products': 'Eco-Friendly Period Products',
      'article_pms_vs_pmdd': 'PMS vs PMDD: What\'s the Difference?',
      'article_exercise_cycle': 'Exercise During Your Menstrual Cycle',
      'read_time': 'min read',
      'author': 'Author',
      'published_date': 'Published',
      'learn_more': 'Learn More',
      'open_article': 'Open Article',
      
      // Authentication
      'signup': 'Sign Up',
      'login': 'Login',
      'name': 'Name',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'signup_here': 'Sign up here',
      'login_here': 'Login here',
      'agree_terms': 'I agree to Terms and Conditions',
      'password_8_chars': 'Password must be at least 8 characters',
      'password_match': 'Passwords do not match',
      'invalid_email': 'Please enter a valid email',
      'email_already_in_use': 'Email is already in use',
      'user_not_found': 'User not found',
      'wrong_password': 'Wrong password',
      'weak_password': 'Password is too weak',
      'missing_fields': 'Please fill in all fields',
      'password_reset_sent': 'Password reset email sent! Check your inbox',
      'no_account_with_email': 'No account found with this email',
      'reset_password': 'Reset Password',
      'send_reset_email': 'Send Reset Email',
      'check_email': 'Check your email for password reset instructions',
      
      // Profile Settings
      'profile_settings': 'Profile Settings',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter your full name',
      'age': 'Age',
      'enter_age': 'Enter your age',
      'upload_photo': 'Tap to upload photo',
      'select_image_source': 'Select Image Source',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'image_selected': 'Image selected successfully',
      'image_captured': 'Image captured successfully',
      'failed_pick_image': 'Failed to pick image',
      'failed_capture_image': 'Failed to capture image',
      'profile_updated': 'Profile updated successfully',
      'failed_save_profile': 'Failed to save profile',
      'updating_profile': 'Updating profile...',
      'uploading_image': 'Uploading image...',
      'image_too_large': 'Image size is too large (max 5MB)',
      'invalid_image_format': 'Invalid image format',
      
      // Common
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'error': 'Error',
      'success': 'Success',
    },
    'bn': {
      // Splash Screen
      'lets_started': 'শুরু করুন',
      
      // Onboarding
      'track_cycle_easily': 'আপনার চক্র সহজে ট্র্যাক করুন',
      'track_cycle_desc': 'এক জায়গায় আপনার পিরিয়ড, ওভুলেশন\nএবং স্বাস্থ্য পর্যবেক্ষণ করুন।',
      'chat_dr_sia': 'ডাক্তার সিয়া এআই চ্যাটবট\n এর সাথে কথা বলুন',
      'chat_dr_sia_desc': 'পিরিয়ড স্বাস্থ্য সম্পর্কে যেকোনো\nপ্রশ্ন নিরাপদে জিজ্ঞাসা করুন।',
      'safe_community': 'নিরাপদ কমিউনিটি ও\nবিশ্বস্ত পণ্য',
      'safe_community_desc': 'আত্মবিশ্বাসের সাথে সংযুক্ত হন\nএবং কেনাকাটা করুন।',
      'next': 'পরবর্তী',
      'skip': 'এড়িয়ে যান',
      
      // Profile Completion
      'complete_profile': 'আপনার প্রোফাইল সম্পূর্ণ করুন',
      'name_optional': 'নাম (ঐচ্ছিক)',
      'age_group': 'বয়স গ্রুপ',
      'cycle_length': 'চক্র দৈর্ঘ্য (দিন)',
      'last_period_date': 'শেষ পিরিয়ডের তারিখ',
      'period_duration': 'পিরিয়ড স্থায়িত্ব (দিন)',
      'continue_btn': 'চালিয়ে যান',
      'invalid_date': 'অবৈধ তারিখ বিন্যাস',
      'period_days': 'দিন',
      'fill_required': 'সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন',
      
      // Home Screen
      'hi': 'হাই',
      'quick_actions': 'দ্রুত পদক্ষেপ',
      'view_tracker': 'ট্র্যাকার দেখুন',
      'chat_with_ai': 'এআই এর সাথে চ্যাট করুন',
      'log_symptoms': 'লক্ষণ\nলিখুন',
      'shop': 'কেনাকাটা',
      'community': 'কমিউনিটি',
      'article': 'টপ আর্টিকেলস',
      'articles': 'টপ আর্টিকেলস',
      'helpline': 'হেল্পলাইন',
      'day_of_cycle': 'দিন',
      'of_your_cycle': 'আপনার চক্রের,',
      'feeling': 'অনুভূতি:',
      'low_energy': 'কম শক্তি 💙',
      'reminder': 'অনুস্মারক',
      // 'next_period': 'পরবর্তী পিরিয়ড ৫ দিনে',
      'shurokkha': 'সুরক্ষা',
      'women_health': 'মহিলা স্বাস্থ্য অ্যাপ',

      // Settings Screen
      'settings': 'সেটিংস',
      'change_language': 'ভাষা পরিবর্তন করুন',
      'change_pin': 'পিন পরিবর্তন করুন',
      'privacy_policy': 'গোপনীয়তা নীতি',
      'notifications': 'বিজ্ঞপ্তি',
      'logout': 'লগআউট',
      'account_security': 'অ্যাকাউন্ট এবং নিরাপত্তা',
      'privacy_data': 'গোপনীয়তা এবং ডেটা',
      'dark_mode': 'ডার্ক মোড সক্ষম করুন',
      'delete_data': 'সমস্ত ডেটা মুছুন',
      'your_data_safe': 'আপনার ডেটা নিরাপদ এবং সুরক্ষিত',
      'tips_messages': 'টিপস ও অনুপ্রেরণামূলক বার্তা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'english': 'English',
      'bengali': 'বাংলা',

      // PIN
      'set_pin': 'পিন সেট করুন',
      'enter_pin': 'পিন প্রবেশ করুন',
      'pin_must_be_4': 'পিন ৪ সংখ্যা হতে হবে',
      'pin_mismatch': 'পিন মিলেনি',
      'incorrect_pin': 'ভুল পিন',
      'confirm_pin': 'পিন নিশ্চিত করুন',

      // Navigation
      'home': 'হোম',
      'calendar': 'ক্যালেন্ডার',
      'chat': 'চ্যাট',
      'store': 'স্টোর',
      
      // Period Tracker
      'period_tracker': 'পিরিয়ড ট্র্যাকার',
      'cycle_info': 'চক্র তথ্য',
      'track_period': 'আপনার পিরিয়ড ট্র্যাক করুন',
      
      // Chat
      'chat_with_dr_sia': 'ডাক্তার সিয়ার সাথে চ্যাট করুন',
      'ask_question': 'এখানে আপনার প্রশ্ন জিজ্ঞাসা করুন...',
      
      // Community
      'join_community': 'আমাদের কমিউনিটিতে যোগ দিন',
      'share_experiences': 'অন্যদের সাথে অভিজ্ঞতা শেয়ার করুন',
      
      // Shop
      'trusted_products': 'বিশ্বস্ত পণ্য',
      'shop_essentials': 'স্বাস্থ্য প্রয়োজনীয় জিনিস কিনুন',
      
      // Articles
      'health_articles': 'স্বাস্থ্য নিবন্ধ',
      'read_articles': 'সহায়ক নিবন্ধ পড়ুন',
      
      // Helpline
      'emergency_helpline': 'জরুরি হেল্পলাইন',
      'need_help': 'সাহায্যের প্রয়োজন? আমাদের হেল্পলাইন যোগাযোগ করুন',
      
      // Health Tips
      'health_tips': 'স্বাস্থ্য টিপস',
      'daily_tips': 'দৈনিক স্বাস্থ্য টিপস এবং পরামর্শ',
      
      // Period Reminder Card
      'period_reminder': 'পিরিয়ড অনুস্মারক',
      'active_period': 'সক্রিয় পিরিয়ড',
      'of': 'এর',
      'day_remaining': 'দিন বাকি',
      'days_remaining': 'দিন বাকি',
      'next_period_in': 'পরবর্তী পিরিয়ড',
      'day': 'দিনে',
      'days': 'দিনে',
      'you_are_on_day': 'আপনি Day-তে আছেন',
      'cycle_progress': 'Cycle Progress',
      'current_day': 'বর্তমান Day',
      'days_until': 'Days পর্যন্ত',
      'days_left': 'Days বাকি',
      'next_next_period': 'পরবর্তী Period',
      'phase_menstruation': 'Phase: Menstruation (মাসিক)',
      'phase_follicular': 'Phase: Follicular (শক্তিশালী)',
      'phase_ovulation': 'Phase: Ovulation (সর্বোচ্চ)',
      'phase_luteal': 'Phase: Luteal (বিশ্রামের সময়)',
      'phase_cycle_begin': 'Phase: Cycle শুরু',
      
      // Additional Translations for Screens
      'flow_intensity': 'Flow Intensity',
      'pain_levels': 'Pain Levels',
      'mood': 'মানসিক অবস্থা',
      'low': 'কম',
      'medium': 'মাঝারি',
      'high': 'বেশি',
      'no_pain': 'কোনো ব্যথা নেই',
      'moderate': 'মাঝারি',
      'severe': 'গুরুতর',
      'good': 'ভাল',
      'neutral': 'স্বাভাবিক',
      'none': 'কোনো নয়',
      'emotional': 'আবেগপূর্ণ',
      'anxious': 'উদ্বিগ্ন',
      'energetic': 'শক্তিশালী',
      'save_symptoms': 'Symptoms সংরক্ষণ করুন',
      'symptoms_logged': 'Symptoms সফলভাবে লগ করা হয়েছে!',
      'online_ready': 'অনলাইন এবং সাহায্য করতে প্রস্তুত',
      'sort_by': 'সাজান',
      'newest': 'নতুনতম',
      'oldest': 'সবচেয়ে পুরনো',
      'short_reads': 'ছোট পড়ার বিষয়',
      'filter': 'ফিল্টার',
      'all': 'সব',
      'emergency': 'জরুরি',
      'mental_health': 'মানসিক স্বাস্থ্য',
      'no_saved_articles': 'কোনো সংরক্ষিত নিবন্ধ নেই',
      'bookmark_articles': 'নিবন্ধগুলি বুকমার্ক করুন সংরক্ষণ করতে',
      'online': 'অনলাইন',
      'status_online': 'অনলাইন',
      'period': 'Period',
      'follicular': 'Follicular',
      'ovulation': 'Ovulation',
      'cycle_phases': 'Cycle Phases',
      'your_menstrual_phase': 'আপনার Menstrual Phase',
      'fertile_window': 'Fertile সময় (সবচেয়ে Fertile)',
      'pms_period': 'PMS Period',
      'pms_description': 'Period এর ২-৩ দিন আগে',
      'set_your_period': 'আপনার Period সেট করুন',
      'choose_preferred_method': 'আপনার পছন্দের পদ্ধতি বেছে নিন',
      'period_start_date': 'Period শুরুর তারিখ',
      'set_when_started': 'আপনার Period কখন শুরু হয়েছে তা সেট করুন',
      'period_start_end': 'Period এর শুরু এবং শেষ',
      'set_both_dates': 'শুরু এবং শেষ উভয় তারিখ সেট করুন',
      'set_period_date': 'Prediction দেখতে আপনার Period এর তারিখ সেট করুন।',
      'current_cycle': 'বর্তমান Cycle',
      'period_in_days': '{days} দিনে',
      'fertility_ovulation': 'Fertility এবং Ovulation',
      'high_fertility': '🔥 উচ্চ Fertility - এখন সেরা সময়!',
      'ovulation_in': '{days} দিনে Ovulation',
      'pms_prediction': 'PMS Prediction',
      'pms_upcoming': '{days} দিনে PMS শুরু হবে',
      'cycle_history': 'Cycle History',
      'future_predictions': 'ভবিষ্যতের Prediction',
      'welcome_hafsa': 'Hafsa AI তে স্বাগতম',
      'personal_health_companion': 'আপনার ব্যক্তিগত Health সঙ্গী',
      'private_secure': '१००% ব্যক্তিগত এবং নিরাপদ\nAI Health Assistant',
      'suggested_questions': 'সাজেস্টেড প্রশ্ন',
      'ask_hafsa': 'Hafsa কে প্রশ্ন করুন...',
      'daily_tip': 'Daily টিপস',
      'search_articles': 'Articles খুঁজুন...',
      'sort_by_label': 'সাজান:',
      'articles_tab': 'Articles',
      'favorites_tab': 'Favorites',
      'no_articles': 'কোনও Article পাওয়া যায়নি',
      'no_favorites': 'এখনও কোনও Bookmarked Article নেই',
      'bookmark_to_save': 'সংরক্ষণ করতে Articles এ Bookmark করুন',
      
      // Health Tips Screen
      'menstrual_health': 'Period সম্পর্কে স্বাস্থ্য ও স্বাস্থ্যবিধি',
      'sanitary_products': 'Sanitary পণ্য সচেতনতা',
      'proper_hygiene': 'সঠিক Hygiene অনুশীলন',
      'period_comfort': 'Period Comfort এবং Cramp Relief',
      'nutrition_energy': 'পুষ্টি এবং শক্তি (বাংলাদেশী খাবার)',
      'iron_rich_foods': 'Iron সমৃদ্ধ খাবার',
      'hydration': 'পানি পান',
      'energy_boosters': 'Energy বৃদ্ধিকারী',
      'avoiding_heavy_foods': 'ভারী খাবার এড়ানো',
      'pms_mood': 'PMS এবং মেজাজ ব্যবস্থাপনা',
      'emotional_support': 'মানসিক সহায়তা টিপস',
      'daily_routine': 'Daily রুটিন সামঞ্জস্য',
      'exercise_lifestyle': 'ব্যায়াম এবং Lifestyle',
      'light_exercise': 'হালকা ব্যায়ামের পরামর্শ',
      'healthy_habits': 'স্বাস্থ্যকর অভ্যাস',
      'fertility_ovulation_awareness': 'Fertility এবং Ovulation সচেতনতা',
      'fertile_window_tips': 'Fertile সময় টিপস',
      'family_planning': 'Family পরিকল্পনা টিপস',
      
      // Helpline Screen
      'select_category': 'Category বেছে নিন',
      'emergency_services': 'Emergency সেবা',
      'mental_health_support': 'Mental স্বাস্থ্য সহায়তা',
      'women_health_services': 'নারী স্বাস্থ্য সেবা',
      'available': 'উপলব্ধ',
      'verified': 'Verified',
      'emergency_medical': 'জরুরি চিকিৎসা Emergency পরিস্থিতির জন্য',
      'mental_health_counseling': 'Mental Health সহায়তা এবং Counseling (বিনামূল্যে ও Confidential)',
      'reproductive_health': 'Reproductive স্বাস্থ্য সেবা এবং পরামর্শ',
      'call_now': 'এখনই কল করুন',
      'copy_number': 'নম্বর Copy করুন',
      
      // Community Screen
      'community_title': 'Shurokkha কমিউনিটি',
      'chat_rooms': 'চ্যাট রুমস',
      'peer_support_chat': 'সহকর্মী সহায়তা চ্যাট',
      'create_new_post': 'নতুন পোস্ট তৈরি করুন',
      'share_your_experience': 'আপনার অভিজ্ঞতা শেয়ার করুন...',
      'select_feeling': 'আপনার অনুভূতি নির্বাচন করুন',
      'select_topic': 'বিষয় নির্বাচন করুন',
      'write_message': 'আপনার বার্তা লিখুন',
      'photo': 'ছবি',
      'location': 'অবস্থান',
      'private': 'গোপনীয়',
      'safe_space': 'নিরাপদ স্থান',
      'anonymous_username': 'বেনামী ব্যবহারকারী',
      'soon_available': 'শীঘ্রই উপলব্ধ হবে',
      'post_created': 'পোস্ট করা হয়েছে ✓',
      'shared_experiences': 'শেয়ার করা অভিজ্ঞতা',
      'people_shared': 'জন তাদের অভিজ্ঞতা শেয়ার করেছে',
      'post_comment': 'মন্তব্য পোস্ট করুন',
      'write_comment': 'আপনার চিন্তা বা অভিজ্ঞতা শেয়ার করুন...',
      'post': 'পোস্ট করুন',
      'supports': 'সমর্থন',
      'comments': 'মন্তব্য',
      'saves': 'সংরক্ষণ',
      'view_all': 'সব দেখুন',
      'expert_reply': 'বিশেষজ্ঞ উত্তর',
      
      // Shop Screen - Products (Bengali)
      'ultra_comfort_pads': 'অতি আরামদায়ক প্যাড',
      'menstrual_cup': 'Period Cup',
      'wellness_kit': 'Wellness Kit',
      'night_pads': 'রাতের প্যাড',
      'organic_cotton_pads': 'জৈব সুতির প্যাড',
      'pain_relief_kit': 'Pain Relief Kit',
      'heating_pad': 'হিটিং প্যাড',
      'category_pads': 'প্যাড',
      'category_cups': 'Cup',
      'category_wellness': 'সুস্থতা',
      'category_hygiene': 'স্বাস্থ্যবিধি',
      'category_nutrition': 'পুষ্টি',
      'best_seller': 'সবচেয়ে জনপ্রিয়',
      'recommended': 'পরামর্শকৃত',
      'add_to_cart': 'কার্টে যোগ করুন',
      'buy_now': 'এখনই কিনুন',
      'rating': 'রেটিং',
      'original_price': 'মূল মূল্য',
      'read_more': 'আরও পড়ুন',
      
      // Article Screen (Bengali)
      'article_understanding_cycle': 'আপনার Period Cycle বুঝুন',
      'article_period_myths': 'Period সম্পর্কিত ভুল ধারণা ভেঙে ফেলুন',
      'article_natural_remedies': 'Period Pain এর প্রাকৃতিক প্রতিকার',
      'article_nutrition_tips': 'ভাল Cycle এর জন্য পুষ্টি টিপস',
      'article_mental_health': 'মানসিক স্বাস্থ্য এবং আপনার Cycle',
      'article_eco_products': 'পরিবেশ বান্ধব Period পণ্য',
      'article_pms_vs_pmdd': 'PMS এবং PMDD: পার্থক্য কি?',
      'article_exercise_cycle': 'আপনার Cycle এ ব্যায়াম',
      'read_time': 'মিনিট পড়া',
      'author': 'লেখক',
      'published_date': 'প্রকাশিত',
      'learn_more': 'আরও জানুন',
      'open_article': 'Article খুলুন',
      
      // Authentication
      'signup': 'সাইন আপ করুন',
      'login': 'লগইন করুন',
      'name': 'নাম',
      'email': 'ইমেইল',
      'password': 'পাসওয়ার্ড',
      'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'dont_have_account': 'অ্যাকাউন্ট নেই?',
      'already_have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
      'signup_here': 'এখানে সাইন আপ করুন',
      'login_here': 'এখানে লগইন করুন',
      'agree_terms': 'আমি শর্তাবলী এবং শর্তাবলী সম্মত হই',
      'password_8_chars': 'পাসওয়ার্ড কমপক্ষে 8 টি অক্ষর হতে হবে',
      'password_match': 'পাসওয়ার্ড মিলেনি',
      'invalid_email': 'দয়া করে একটি বৈধ ইমেইল প্রবেশ করুন',
      'email_already_in_use': 'ইমেইল ইতিমধ্যে ব্যবহৃত হচ্ছে',
      'user_not_found': 'ব্যবহারকারী খুঁজে পাওয়া যায়নি',
      'wrong_password': 'ভুল পাসওয়ার্ড',
      'weak_password': 'পাসওয়ার্ড খুব দুর্বল',
      'missing_fields': 'সমস্ত ক্ষেত্র পূরণ করুন',
      'password_reset_sent': 'পাসওয়ার্ড রিসেট ইমেইল পাঠানো হয়েছে! আপনার ইনবক্স চেক করুন',
      'no_account_with_email': 'এই ইমেইল দিয়ে কোনো অ্যাকাউন্ট পাওয়া যায়নি',
      'reset_password': 'পাসওয়ার্ড পুনরায় সেট করুন',
      'send_reset_email': 'রিসেট ইমেইল পাঠান',
      'check_email': 'পাসওয়ার্ড রিসেট নির্দেশাবলীর জন্য আপনার ইমেইল চেক করুন',
      
      // Profile Settings (Bengali)
      'profile_settings': 'প্রোফাইল সেটিংস',
      'full_name': 'সম্পূর্ণ নাম',
      'enter_full_name': 'আপনার সম্পূর্ণ নাম প্রবেশ করুন',
      'age': 'বয়স',
      'enter_age': 'আপনার বয়স প্রবেশ করুন',
      'upload_photo': 'ফটো আপলোড করতে ট্যাপ করুন',
      'select_image_source': 'ইমেজ উৎস নির্বাচন করুন',
      'gallery': 'গ্যালারি',
      'camera': 'ক্যামেরা',
      'image_selected': 'ইমেজ সফলভাবে নির্বাচন করা হয়েছে',
      'image_captured': 'ইমেজ সফলভাবে ক্যাপচার করা হয়েছে',
      'failed_pick_image': 'ইমেজ নির্বাচন করতে ব্যর্থ',
      'failed_capture_image': 'ইমেজ ক্যাপচার করতে ব্যর্থ',
      'profile_updated': 'প্রোফাইল সফলভাবে আপডেট করা হয়েছে',
      'failed_save_profile': 'প্রোফাইল সংরক্ষণ করতে ব্যর্থ',
      'updating_profile': 'প্রোফাইল আপডেট করা হচ্ছে...',
      'uploading_image': 'ইমেজ আপলোড করা হচ্ছে...',
      'image_too_large': 'ইমেজ আকার খুব বড় (সর্বোচ্চ 5MB)',
      'invalid_image_format': 'অবৈধ ইমেজ ফরম্যাট',
      
      // Common (Bengali)
      'ok': 'ঠিক আছে',
      'cancel': 'বাতিল করুন',
      'save': 'সংরক্ষণ করুন',
      'delete': 'মুছুন',
      'edit': 'সম্পাদনা করুন',
      'close': 'বন্ধ করুন',
      'error': 'ত্রুটি',
      'success': 'সফল',
    },
  };

  static String get(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}
